layout_spectrum: 0.1052615
color:
  saturation: 0.0172496
  brandStrength: 0.8261649
  lightness: 0.7345629
  rhythmicContrast: 0.1797511
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.2103644
name: 'Jordan Franz '
